baseURL = 'https://okulusdev.github.io'
languageCode = 'ru'
title = 'Okulus Dev'
paginate = 100 #frontpage pagination
theme = 'monochrome'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'gruvbox'
    tabWidth = 4

[params]
	navbar_title = "Okulus Dev" # default: site's `title`
	footer = "Copyright © 2023 by OkulusDev" # default: None
	enable_toc = true # default: true
	enable_collapsible_toc = true # default: false
	enable_collapsible_changelogs = false # default: false
	enable_math = true
	enable_site_search = true # default: false
	author = "Okulus Dev" # default: no author `meta` tag
	color_scheme = "dark" # "light" or "dark"

  	[params.list_layout]
		enable_group_by_year = false # default: true
		enable_show_date = true # default: true
		enable_pagination = true # default: false
